name: Build and Test

on:
  workflow_call:
    secrets:
      API_BASE_URL:
        required: true
      FRANCHISE_REGISTRY_CONTRACT:
        required: true
      RELATIONSHIP_MODULE_CONTRACT:
        required: true
      LICENSING_MODULE_CONTRACT:
        required: true
      COLLECT_MODULE_CONTRACT:
        required: true
      RPC_PROVIDER_URL:
        required: true
      WALLET_PRIVATE_KEY:
        required: true

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      ## To use Remote Caching, uncomment the next lines and follow the steps below.
      # TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      # TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      NEXT_PUBLIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
      NEXT_PUBLIC_FRANCHISE_REGISTRY_CONTRACT: ${{ secrets.FRANCHISE_REGISTRY_CONTRACT }}
      NEXT_PUBLIC_RELATIONSHIP_MODULE_CONTRACT: ${{ secrets.RELATIONSHIP_MODULE_CONTRACT }}
      NEXT_PUBLIC_LICENSING_MODULE_CONTRACT: ${{ secrets.LICENSING_MODULE_CONTRACT }}
      NEXT_PUBLIC_COLLECT_MODULE_CONTRACT: ${{ secrets.COLLECT_MODULE_CONTRACT }}
      RPC_PROVIDER_URL: ${{ secrets.RPC_PROVIDER_URL }}
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.8.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Fix
        run: pnpm fix

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build