name: External PR

on: 
  pull_request_target:
    types: [opened, synchronize]

jobs:
  authorize:
    if: github.event.pull_request.head.repo.full_name != github.repository
    environment: 'external'
    runs-on: ubuntu-latest
    steps:
      - run: true
  build_and_test:
    needs: authorize
    uses: ./.github/workflows/build-and-test.yaml 
    secrets:
      api_base_url: ${{ secrets.API_BASE_URL }} 
      FRANCHISE_REGISTRY_CONTRACT: ${{ secrets.FRANCHISE_REGISTRY_CONTRACT }}
      RELATIONSHIP_MODULE_CONTRACT: ${{ secrets.RELATIONSHIP_MODULE_CONTRACT }}
      LICENSING_MODULE_CONTRACT: ${{ secrets.LICENSING_MODULE_CONTRACT }}
      COLLECT_MODULE_CONTRACT: ${{ secrets.COLLECT_MODULE_CONTRACT }}
      RPC_PROVIDER_URL: ${{ secrets.RPC_PROVIDER_URL }}
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
  