name: External PR

on: 
  pull_request_target:
    types: [opened, synchronize]

jobs:
  authorize:
    if: github.event.pull_request.head.repo.full_name != github.repository
    environment: 'external'
    runs-on: ubuntu-latest
    steps:
      - run: true
  build_and_test:
    needs: authorize
    uses: ./.github/workflows/build-and-test.yaml 
    with: 
      sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      API_BASE_URL: ${{ secrets.API_BASE_URL }} 
      STORY_PROTOCOL_CONTRACT: ${{ secrets.STORY_PROTOCOL_CONTRACT_ALPHA }}
      IP_ASSET_REGISTRY_CONTRACT: ${{ secrets.IP_ASSET_REGISTRY_CONTRACT_ALPHA }} 
      IP_ORG_CONTROLLER_CONTRACT: ${{ secrets.IP_ORG_CONTROLLER_CONTRACT_ALPHA }}
      RELATIONSHIP_MODULE_CONTRACT: ${{ secrets.RELATIONSHIP_MODULE_CONTRACT_ALPHA }}
      REGISTRATION_MODULE_CONTRACT: ${{ secrets.REGISTRATION_MODULE_CONTRACT_ALPHA }}
      LICENSE_REGISTRY_CONTRACT: ${{ secrets.LICENSE_REGISTRY_CONTRACT_ALPHA }}
      MODULE_REGISTRY_CONTRACT: ${{ secrets.MODULE_REGISTRY_CONTRACT_ALPHA }}
      RPC_PROVIDER_URL: ${{ secrets.RPC_PROVIDER_URL }}
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
  